### PR TITLE
Add more detailed installation and development instructions

### PR DESCRIPTION
**Pull request by SimonKienzler**

### CODE REVIEW

**Comment by SimonKienzler** [comment]
@brumhard One question before I publish this draft PR.

https://github.com/brumhard/primate/blob/abcca91e06f4fd7e358cf39c5dd5b5f2a3fa0e03/app/lib/main.dart#L28

I set this line to

```dart
    grpcWebPort: 8080,
```

in order for the app to be able to communicate with the gRPC server in my local setup. Is this the way to get the local setup working or am I wrong? In the first case, I would add this to the docs, otherwise I'd be happy to add a better approach to the README. I'm not super convinced by this solution because you'd always have to remember to revert the change before comitting 😅

**Comment by brumhard** [comment]
@SimonKienzler that's a good point and I'm not really sure how I did it. I think I might have mocked the responses in the flutter service to not depend on a running backend locally and then added this config setting as soon as I was finished. You might find sth like this in the PR service's history.

Ofc that's far from ideal for the further development and I agree with you that it should not depend on any local file changes.
Maybe we could introduce some local development mode and change the local port depending on that. Maybe there's already some dev mode indicator since there's also this badge in the app bar in development. 

WDYT?

**Comment by brumhard** [comment]
There's the constant [`kDebugMode`](https://stackoverflow.com/questions/49707028/how-to-check-flutter-application-is-running-in-debug) which is enabled when flutter in run in debug mode. That should to the trick.

**Comment by brumhard** [comment]
Sth like this worked for me locally:
```dart
static String get backendHost {
  if (kDebugMode) {
    return 'localhost';
  }
  if (kIsWeb) {
    return Uri.base.host;
  }
  throw Exception("not implemented for a platform other than web");
}

static int get grpcWebPort {
  if (kDebugMode) {
    return 8080;
  }
  if (kIsWeb) {
    return Uri.base.port;
  }
  throw Exception("not implemented for a platform other than web");
}
```
(`kDebugMode` is in the same package as `kIsWeb`)

**Comment by SimonKienzler** [comment]
Will add your solution to this PR shortly and then publish it :)

**Review by brumhard — APPROVED** [review]
Really appreciate the docs effort 👯

**Pull request merged**
